#                //========================//
#                //****  Michal Glos   ****//
#                //**      xglosm01       **//
#                //*         IOS          *//
#                //**       Proj2        **//
#                //****   28.4.2019    ****//
#                //========================//

CC=gcc
CFLAGS= -std=c99 -pedantic -Wall -Wextra -Werror
ENDFLAGS= -lrt -lpthread -pthread

proj2: proj2.c
	$(CC) $(CFLAGS) proj2.c -o proj2 $(ENDFLAGS)